# Names in Group: AJ Garner, Mitchell L. Pohar
# Date: 27 March 2024
# Class: CPSC 3220
# Assignment: HW2


# To compile: make
# To clean: make clean


compile:
	gcc -Wall sched.c -o sched

clean:
	rm sched