# Member Names: AJ Garner, Mitchell Pohar
# Date: 17 April 2024
# Class: CPSC 3220
# Assignment: Homework 3


# To compile: make
# To run: make run
# To clean: make clean

# Compile the new great file system into driver 3
compile:
	gcc -g grtfs_1.c grtfs_2.c grtfs_driver3.c -o grtfs_driver3.out

# Run new 4096 great file system with driver 3
run:
	./grtfs_driver3.out

# Clean all .out files from the directory
clean:
	rm -rf *.out