-- ## Problem 5
-- 
-- Enable auto increment on the primary key in the CUSTOMER table.
-- The values should start with 2000.
-- 
ALTER TABLE CUSTOMER DROP PRIMARY KEY;
ALTER TABLE CUSTOMER MODIFY CUST_NUM INT AUTO_INCREMENT;
ALTER TABLE CUSTOMER AUTO_INCREMENT = 2000;
ALTER TABLE CUSTOMER ADD PRIMARY KEY (CUST_NUM);