# Member Names: AJ Garner, Mitchell L. Pohar
# Date: 10 April 2024
# Class: CPSC 3600
# Assignment: Assignment 3


# To compile: make
# To clean: make clean

compile:
	gcc -Wall -g -o udping -pthread -std=gnu99 udping.c DieWithMessage.c AddressUtility.c
clean:
	rm -rf udping
